### ISSUE TITLE
Error load app

### ISSUE THREAD

**Issue by tarcisiodier** [robertop23/web2py_vuejs_vuetify#3]
Traceback (most recent call last):
  File "/Users/tarcisiodier/Projetos/linknabio/web2py/gluon/restricted.py", line 219, in restricted
    exec(ccode, environment)
  File "/Users/tarcisiodier/Projetos/linknabio/web2py/applications/web2py_vuejs_vuetify/views/default/index.html", line 22, in <module>
    {% import urllib2 %}
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 404: NOT FOUND

**Comment by vinidiktov-edsd** [comment]
What is your browser's locale? If it isn't English, the app won't find the file on this line in default/index.html: 

{% lng_file_url = 'http://{}:{}/{}/static/public/lang/{}.json'.format(request.env.remote_addr, request.env.server_port, request.application, T.accepted_language[:2])%}

Can you try this line instead? 

{% lng_file_url = 'http://{}:{}/{}/static/public/lang/en.json'.format(request.env.remote_addr, request.env.server_port, request.application)%}

**Comment by vinidiktov-edsd** [comment]
If that doesn't work, try this instead:
{% lng_file_url = '{}://{}/{}/static/public/lang/en.json'.format(request.env.wsgi_url_scheme,
            request.env.http_host, request.application) %}

**Comment by robertop23** [comment]
Please tell us if the vinidiktov sample is fixing your error, I think that
we need add some try at this point to avoid this

**Comment by marcomansilla** [comment]
I can confirm that @vinidiktov-edsd answer does fix the issue.

**Comment by robertop23** [comment]
can you send a pull request?
